baseURL = 'https://jxinging.github.io/cloudiac-blog'
title = 'CloudIaC Blog'
theme = "ananke"
copyright = "杭州云霁科技有限公司"
enableEmoji = true
enableRobotsTXT = true
languageCode = 'zh'
defaultContentLanguage = 'zh'
hasCJKLanguage = true
sectionPagesMenu = "main"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = "/images/logo.svg"
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 5
  show_reading_time = true

[[params.ananke_socials]]
name = "github"
url = "https://github.com/idcos/cloudiac"

